#!/bin/bash

set -e

# Get the current version
CURRENT_VERSION=$(ruby -Ilib -r dotenv/version -e "puts Dotenv::VERSION")
echo "Current Version: ${CURRENT_VERSION}"

# Get a new version
echo -n "New Version: "
read NEW_VERSION

# Update the version
sed -i '' "s/$CURRENT_VERSION/$NEW_VERSION/" lib/dotenv/version.rb

# Grab a log of the merged pull requests
CHANGELOG=$(
  git log master...v2.0.1 --merges --format="%s | %b" \
  | grep "Merge pull request" \
  | sed -E "s/Merge pull request (#[0-9]+) from ([^\/]+)\/[^ ]+ \| (.*)/\* \1: \3 - @\2/"
)

sed -i '' "/# Changelog/a \n\n## $NEW_VERSION - $(date "+%b %d %Y")\n\n$CHANGELOG\n" Changelog.md

git co -b release-$NEW_VERSION
git add lib/dotenv/version.rb Changelog.md
git commit -m "Prepare for $NEW_VERSION release"

# TODO: open pull request
